blank_issues_enabled: true
contact_links:
  - name: HGN Community Forum
    url : https://forums.hypergamer.net/
    about: Community forums to ask questsions that are not bugs of feature requests.
    
  